name: CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get -y install discount python3-venv make linkchecker tox
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install tox discount
        # Prepend optional brew binary directories to PATH
        echo "$(brew --prefix)/opt/python/libexec/bin" >> $GITHUB_PATH
    - name: Test
      run: |
        tox
        if [ "$RUNNER_OS" = "Linux" ]; then
          # Prepend user bin directory to PATH
          echo $(python -c "import os; import sysconfig; print(sysconfig.get_path('scripts', f'{os.name}_user'))") >> $GITHUB_PATH
          pip install --user .
          linton serve --port 8000 ./linton/init-pages & linkchecker http://localhost:8000/index.html
        fi
